name: Desplegar CSS y HTML en GitHub Pages

on:
  push:
    branches:
      - main  # Cambia si tu rama principal no es 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Publica desde la raíz (ajusta si tienes carpeta `dist` o `build`)
