name: Validar CSS con Stylelint

on:
  push:
    paths:
      - '**/*.css'
  pull_request:
    paths:
      - '**/*.css'

jobs:
  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Stylelint
        run: npm install stylelint stylelint-config-standard --save-dev

      - name: Crear configuración de Stylelint (si no existe)
        run: |
          if [ ! -f .stylelintrc.json ]; then
            echo '{
              "extends": "stylelint-config-standard"
            }' > .stylelintrc.json
          fi

      - name: Ejecutar Stylelint
        run: npx stylelint "**/*.css"
