name: Validar HTML

on:
  push:
    paths:
      - '**.html'
  pull_request:
    paths:
      - '**.html'

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Instalar HTMLHint
      run: npm install -g htmlhint

    - name: Validar archivos HTML
      run: htmlhint "**/*.html"
